In [1]:
import numpy as np

In [3]:
#打印numpy的版本号
np.__version__

'1.15.4'

In [5]:
#产生Bool数组
np.ones((3, 3), dtype = np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
#extract all odd numbers in arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.compress(condition = arr % 2 == 0, a = arr, axis = 0)

In [12]:
#Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 ==0] = -1
arr

In [15]:
#Convert a 1D array to a 2D array with 2 rows
np.arange(0, 10).reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
#Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#注意np.concatenate的参数
np.concatenate((a, b), axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
#Stack the arrays a and b horizontally
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
#Create the following pattern without hardcoding. 
#Use only numpy functions and the below input array a
a = np.array([1, 2, 3])
#np.repeat和np.title
np.concatenate((np.repeat(a, 3), np.tile(a, 3)), axis = 0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

######  How to get the common items between two python numpy arrays?

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [28]:
#np.intersect1d
np.intersect1d(a, b)

array([2, 4])

###### How to remove from one array those items that exist in another?

In [29]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [30]:
# From a remove all of b
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [33]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#用np.where
np.where(a == b)

(array([1, 3, 5, 7]),)

###### How to make a python function that handles scalars to work on numpy arrays?

In [34]:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [38]:
help(np.vectorize)

Help on class vectorize in module numpy.lib.function_base:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns an single or tuple of numpy array as
 |  output. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The output data type. It must be specified as either a string of
 |      typecode ch

In [37]:
pair_max = np.vectorize(maxx, otypes = [float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

###### Swap columns 1 and 2 in the array arr

In [50]:
arr = np.arange(9).reshape(3,3)

In [69]:
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [74]:
#Swap rows 1 and 2 in the array arr
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

###### Reverse the rows of a 2D array arr，记住这个trick！！！！！！！！！

In [86]:
arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [87]:
#Reverse the columns of a 2D array arr
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [91]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
np.random.uniform(5, 10, size = (5, 3))

array([[7.24793988, 5.83488798, 5.43943121],
       [6.40217545, 5.25349891, 6.41577033],
       [9.18505972, 7.95904305, 9.46147616],
       [6.59534199, 7.73114549, 7.65430371],
       [6.88269353, 6.81840214, 5.52058149]])

######  How to print only 3 decimal places in python numpy array? 查阅np.set_printoptions的其他用法

In [94]:
rand_arr = np.random.random((5,3))

In [96]:
#用np.set_printoptions
np.set_printoptions(precision = 3)
rand_arr

array([[0.627, 0.826, 0.175],
       [0.144, 0.316, 0.674],
       [0.959, 0.589, 0.423],
       [0.68 , 0.162, 0.054],
       [0.661, 0.81 , 0.22 ]])

###### How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [5]:
#np.genfromtxt 函数
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris = np.genfromtxt(url, delimiter=',', dtype=None)
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

/home/zhangzijie_dlut/miniconda3/envs/zzj/lib/python3.6/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [6]:
iris[:3]

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [10]:
# Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [12]:
np.mean(sepallength), np.median(sepallength), np.std(sepallength)

(5.843333333333334, 5.8, 0.8253012917851409)

In [13]:
# Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 
#so that the minimum has value 0 and maximum has value 1.
(sepallength - np.min(sepallength)) / (np.max(sepallength) - np.min(sepallength))

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [14]:
#np.ptp函数求数组的range
(sepallength - np.min(sepallength)) / np.ptp(sepallength)

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [15]:
#Compute the softmax score of sepallength.
def softmax(x):
    e_x = np.exp(x - np.max(x)) #减去最大值避免溢出
    return e_x / e_x.sum(axis=0)
softmax(sepallength)

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [18]:
#Find the 5th and 95th percentile of iris's sepallength
np.percentile(sepallength, [5, 95])

array([4.6  , 7.255])

In [19]:
#Insert np.nan values at 20 random positions in iris_2d dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

#注意这个用法！！！！！得到非空数据的index
i, j = np.where(iris_2d)
#插入数据, np.random.choice
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

In [24]:
# Method 2,生成随机整数
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

###### 33. How to find the position of missing values in numpy array?

In [27]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [32]:
np.where(np.isnan(iris_2d))

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   8,   9,  10,  11,
         12,  13,  14,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  24,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
         34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
         47,  48,  49,  50,  51,  52,  53,  53,  54,  55,  56,  57,  58,
         58,  59,  60,  60,  61,  62,  63,  64,  65,  66,  66,  67,  67,
         68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  87,  88,  89,  90,  91,
         92,  93,  94,  94,  95,  96,  97,  98,  98,  99, 100, 101, 102,
        103, 103, 104, 105, 106, 107, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 137, 138,
        138, 139, 140, 141, 142, 143, 143, 144, 144, 145, 146, 147, 148,
        149]),
 array([4, 4, 4, 4, 4, 4, 4, 4, 1, 4

In [3]:
# Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and 
# sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [7]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
np.compress(condition = condition, a = iris_2d, axis = 0)

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [10]:
# Select the rows of iris_2d that does not have any nan value.
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# 用np.apply_along_axis对每一行检查
# 连用np.any 与 np.isnan
selected_row = \
np.apply_along_axis(func1d = lambda x: ~np.any(np.isnan(x)), arr = iris_2d, axis = 1)
#用np.compress来做mask
np.compress(condition = selected_row, axis = 0, a = iris_2d)

In [33]:
#Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#计算相关系数
np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])

In [41]:
# Find out if iris_2d has any missing values
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.all(~np.isnan(iris_2d))

In [45]:
#. Replace all ccurrences of nan with 0 in numpy array
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0.

In [56]:
# Find the unique values and the count of unique values in iris's species
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#用np.unique
np.unique(iris[:, 4], return_counts)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50]))

######  How to convert a numeric to a categorical (text) array?

In [59]:
# Bin the petal length (3rd) column of iris_2d to form a text array, 
# such that if petal length is:

##Less than 3 --> 'small'
##3-5 --> 'medium'
##'>=5 --> 'large'

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
petal_length = iris_2d[:, 2]

def to_category(a):
    if a < 3:
        return 'small'
    elif 3<=a<5:
        return 'medium'
    else:
        return 'large'
func = np.vectorize(pyfunc = to_category)
func(petal_length)

In [69]:
#另外的解法

#用np.digitize 来bin数组
petal_length_bins = np.digitize(petal_length, [0, 3, 5, 100])

#map bin to category
label_map = {1 : 'small', 2 : 'medium', 
             3 : 'large', 4 : np.nan}
petal_length_cats = np.array([label_map[x] for x in petal_length_bins])

In [82]:
#Create a new column for volume in iris_2d, 
#where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length = iris_2d[:, 2]
sepal_length = iris_2d[:, 0]
volumn = 1/3 * np.pi * petal_length * sepal_length * sepal_length
#注意，用np.newaxis把volumn由行向量转换成列向量
np.hstack((iris_2d, volumn[:, np.newaxis]))

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.81326516e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.83832424e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.77148198e+01],
       [5.40000000e+00, 3.7000

######  How to do probabilistic sampling in numpy?

In [25]:
# Randomly sample iris's species such that 
#setose is twice the number of versicolor and virginica
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
species = iris_2d[:, 4]

In [26]:
#help(np.r_)

In [27]:
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.5, num = 50), 
              np.linspace(0.501, .750, num = 50),
              np.linspace(0.751, 1.0, num = 50)]

In [28]:
#help(np.searchsorted)

In [29]:
#把第二个参数的元素插入到第一个参数的已排好序的数组中，保持第一个参数的数组原顺序不变 返回index
index = np.searchsorted(probs, np.random.random(150))

In [30]:
species_out = species[index]
np.unique(species_out, return_counts = True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([77, 37, 36]))

In [31]:
#What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

mask = (iris[:, 4] == b'Iris-setosa')
iris_setosa = np.compress(condition = mask, a = iris, axis = 0)
#注意要用np.unique排除重复值！
np.unique(np.sort(iris_setosa[:, 2].astype(float)))[-2]

In [52]:
#Sort the iris dataset based on sepallength column
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sepal_length = iris[:, 0].astype(float)
sorted_idx = np.argsort(sepal_length)
np.take(indices = sorted_idx, a = iris, axis = 0)

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

In [55]:
#Find the most frequent value of petal length (3rd column) in iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
values, counts = np.unique(iris[:, 2].astype(float), return_counts = True)
values[np.argmax(counts)]

1.5

In [56]:
#Find the position of the first occurrence of a value 
#greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petal_width = iris[:, 3].astype(float)

#np.argwhere
np.argwhere(petal_width > 1.0)[0][0]

###### How to replace all values greater than a given value to a given cutoff?

In [71]:
#From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

#解法一, np.clip
np.clip(a, a_min = 10, a_max = 30)
#揭发二, np.where
np.where(a < 10, 10, np.where(a > 30, 30, a))

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [74]:
#Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.unique(np.sort(a))[-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [87]:
#Compute the counts of unique values row-wise.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
#获得数组的值域
arr_range = np.unique(arr)
#写一个针对行的函数
def value_counts(a):
    res = np.zeros(len(arr_range))
    for x in a:
        res[x - 1] +=1
    return res
#然后apply每一行
np.apply_along_axis(func1d = value_counts, arr = arr, axis = 1)

array([[1., 0., 2., 1., 1., 1., 0., 2., 2., 0.],
       [2., 1., 3., 0., 1., 0., 1., 0., 1., 1.],
       [0., 3., 0., 2., 3., 1., 0., 1., 0., 0.],
       [1., 0., 2., 1., 0., 1., 0., 2., 1., 2.],
       [2., 2., 2., 0., 0., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 2., 0., 0., 2., 1.]])

In [92]:
#Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
#用np.concatenate
np.concatenate(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### How to generate one-hot encodings for an array in numpy?

In [98]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
#获取值域
arr_range = np.unique(arr)
#构造映射
one_hot_map = {x : i for i, x in enumerate(arr_range)}

res = np.zeros((len(arr), len(arr_range)), dtype = int)
for i in range(len(arr)):
    res[i, one_hot_map[arr[i]]] = 1

In [99]:
res

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [107]:
#第二种解法
#view不发生复制！！！
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

###### ?????????

In [3]:
# 52 Create row numbers grouped by a categorical variable. 
#Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [11]:
#Create group ids based on a given categorical variable. 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
specie_cat = np.sort(np.unique(species))
cat_map = {x : i for i, x in enumerate(specie_cat)}
res = np.array([cat_map[x] for x in species_small])
res

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
#Create the ranks for the given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=10)
#连用两次np.argsort得到升序的rank
np.argsort(np.argsort(a))

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

In [22]:
#Create a rank array of the same shape as a given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
a

np.argsort(np.argsort(a.ravel())).reshape(a.shape)

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0]])

In [27]:
 #Compute the min-by-max for each row for given 2d numpy array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [28]:
np.apply_along_axis(axis = 1, arr = a, func1d = lambda x: x.min() / x.max())

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [13]:
# Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. 
#First time occurrences should be False.
np.random.seed(100)
a = np.random.randint(0, 5, 10)

unique_value, index = np.unique(a, return_index = True)

res = np.ones(a.shape, dtype = bool)
res[index] = False

res

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [22]:
#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris_ = iris[:, :3].astype(float)
unique_specie = np.unique(iris[:, 4])
res = np.array([
    np.mean(iris_[iris[:, 4] == specie, :], axis = 0)
    for specie in unique_specie
])

In [24]:
res

array([[5.006, 3.418, 1.464],
       [5.936, 2.77 , 4.26 ],
       [6.588, 2.974, 5.552]])

In [21]:
#Drop all nan values from a 1D numpy array
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [22]:
# Compute the euclidean distance between two arrays a and b.
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.sqrt(np.sum((a - b)**2))

6.708203932499369

###### How to find all the local maxima (or peaks) in a 1d array? 好好看

In [26]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [30]:
#np.sign
np.sign(np.diff(a))

array([ 1,  1, -1,  1,  1, -1,  1])

In [31]:
np.diff(np.sign(np.diff(a)))

array([ 0, -2,  2,  0, -2,  2])

In [33]:
np.where(np.diff(np.sign(np.diff(a))) == -2)[0] + 1

array([2, 5])

In [44]:
#Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d 
#subtracts from respective row of a_2d.
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

id(b_1d[:, np.newaxis]) == id(b_1d), id(b_1d[:, None]) == id(b_1d)

a_2d - b_1d[:, np.newaxis]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [45]:
#Find the index of 5th repetition of number 1 in x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

np.where(x == 1)[0][4]

###### 记住这个写法

In [50]:
[i for i, v in enumerate(x) if v == 1]

[0, 2, 3, 7, 8, 10, 11]

In [57]:
#Convert numpy's datetime64 object to datetime's datetime object
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

###### How to compute the moving average of a numpy array?

In [58]:
np.random.seed(100)
Z = np.random.randint(10, size=10)

In [62]:
np.convolve(Z, np.ones(3)/3, mode='valid') 

array([6.33333333, 6.        , 5.66666667, 4.66666667, 3.66666667,
       2.        , 3.66666667, 3.        ])

In [ ]:
#Create a numpy array of length 10, 
#starting from 5 and has a step of 3 between consecutive numbers
