In [1]:
import numpy as np

##### 对两个数组 a 和 b

In [2]:
a = np.arange(0, 10)
b = np.arange(10, 20)

###### np.einsum('i', a) 返回数组a本身

In [5]:
np.einsum('i', a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### np.einsum('i->', a) 返回数组a的元素和，等价于 np.sum(a)

In [7]:
np.einsum('i->', a)

45

###### np.einsum('i, i->i', a, b) 返回数组a和b的广播相乘， 等价于 a * b

In [10]:
np.einsum('i, i -> i', a, b)

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

###### np.einsum('i, i ', a, b) 返回数组a和b的内积， 等价于 np.inner(a, b)

In [12]:
np.einsum('i, i', a, b)

735

###### np.einsum('i, j -> ij' a, b)返回a和b的外积，等价于np.outer(a, b)

In [14]:
np.einsum('i, j -> ij', a, b)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [ 60,  66,  72,  78,  84,  90,  96, 102, 108, 114],
       [ 70,  77,  84,  91,  98, 105, 112, 119, 126, 133],
       [ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152],
       [ 90,  99, 108, 117, 126, 135, 144, 153, 162, 171]])

In [15]:
np.outer(a, b)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [ 60,  66,  72,  78,  84,  90,  96, 102, 108, 114],
       [ 70,  77,  84,  91,  98, 105, 112, 119, 126, 133],
       [ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152],
       [ 90,  99, 108, 117, 126, 135, 144, 153, 162, 171]])

##### 对两个矩阵 A 和 B

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

###### np.einsum('ij', A) 返回A本身

In [18]:
np.einsum('ij', A)

array([[1, 2],
       [3, 4]])

###### np.einsum('ji', A)返回A的转置

In [19]:
np.einsum('ji', A)

array([[1, 3],
       [2, 4]])

###### np.einsum('ii -> i', A)返回A对角线上的元素, 等价于 np.diag(A)

In [21]:
np.einsum('ii -> i', A)

array([1, 4])

###### np.einsum('ii', A)返回A的迹， 等价于np.trace(A)

In [22]:
np.einsum('ii', A)

5

###### np.einsum('ij ->', A)返回A的元素和， 等价于np.sum(A)

In [23]:
np.einsum('ij ->', A)

10

###### np.einsum('ij -> j', A)返回A的列和， 等价于np.sum(A, axis =0)

In [24]:
np.einsum('ij -> j', A)

array([4, 6])

In [25]:
np.sum(A, axis = 0)

array([4, 6])

###### np.einsum('ij -> i', A)返回A的行和， 等价于np.sum(A, axis = 1)

In [26]:
np.einsum('ij -> i', A)

array([3, 7])

In [27]:
np.sum(A, axis = 1)

array([3, 7])

###### np.einsum('ij, ij -> ij', A, B)返回A和B的广播相乘, 等价于 A * B

In [29]:
np.einsum('ij, ij -> ij', A, B)

array([[ 5, 12],
       [21, 32]])

In [30]:
A * B

array([[ 5, 12],
       [21, 32]])

###### np.einsum('ij, ji -> ij', A, B)返回A和B的转置广播相乘, 等价于 A * B.T

In [31]:
np.einsum('ij, ji -> ij', A, B)

array([[ 5, 14],
       [18, 32]])

In [32]:
A * B.T

array([[ 5, 14],
       [18, 32]])

In [34]:
## A * B 再做转置
np.einsum('ij, ij -> ji', A, B)

array([[ 5, 21],
       [12, 32]])

###### np.einsum('ij, ij', A, B) 是A和B的内积， 等价于 np.sum(A * B)

In [35]:
np.einsum('ij, ij', A, B)

70

In [36]:
np.sum(A * B)

70

###### np.einsum('ij, jk', A, B)是A乘以B， 等价于np.dot(A, B)

In [49]:
np.einsum('ij, jk -> ik', A, B)

array([[19, 22],
       [43, 50]])

In [39]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

###### np.einsum('ij, kj -> ikj', A, B) 等价于A的每一行与B做广播乘法， 等价于A[:, None] * B

In [57]:
np.einsum('ij, kj -> ikj', A, B)

array([[[ 5, 12],
        [ 7, 16]],

       [[15, 24],
        [21, 32]]])

In [58]:
A[:, None] * B

array([[[ 5, 12],
        [ 7, 16]],

       [[15, 24],
        [21, 32]]])

###### np.einsum('ij, kl -> ijkl', A, B) 等价于A的每个元素与B做广播乘法， 等价于A[:, :, None, None] * B

In [60]:
np.einsum('ij, kl -> ijkl', A, B)

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

In [62]:
A[:, :, None, None] * B

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

##### 其他

In [40]:
T = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])
x = np.array([0, 1, 2])

In [43]:
(x[:, np.newaxis] * T).sum(axis = 1)

array([ 0, 22, 76])

###### 使用np.einsum避免了reshape， 从而避免了临时变量

In [45]:
np.einsum('i, ij -> i', x, T)

array([ 0, 22, 76])

##### 一些规则

In [46]:
#Repeating letters between input arrays means that 
##values along those axes will be multiplied together. 
#The products make up the values for the output array.

In [47]:
#Omitting a letter from the output means that values along that axis will be summed

In [54]:
#We can return the unsummed axes in any order we like.

In [55]:
#显示了矩阵相乘的过程
np.einsum('ij, jk -> ijk', A, B)

array([[[ 5,  6],
        [14, 16]],

       [[15, 18],
        [28, 32]]])

##### 一些限制

In [63]:
#该函数不能保证data type when summing

In [64]:
#该函数可能不会permute axes in the order inteded

In [65]:
#该函数未必是Numpy最快的，比如np.dot和np.inner用了BLAS